# Generated by Django 5.2 on 2025-07-22 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSummaryTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('email_summary', models.TextField()),
                ('billable_description', models.TextField()),
                ('practice_panther_time_entry_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_minutes', models.IntegerField(default=15, help_text='Duration in minutes')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('matter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_practice_panther', models.BooleanField(default=False)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Summary Time Entry',
                'verbose_name_plural': 'Email Summary Time Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticePantherToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(help_text='OAuth refresh token')),
                ('expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_panther_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PracticePanther Token',
                'verbose_name_plural': 'PracticePanther Tokens',
            },
        ),
        migrations.CreateModel(
            name='PracticePantherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_panther_user_id', models.CharField(help_text='PracticePanther User ID', max_length=255)),
                ('default_matter_id', models.CharField(blank=True, help_text='Default matter for time entries', max_length=255, null=True)),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default hourly rate', max_digits=10)),
                ('auto_create_time_entries', models.BooleanField(default=True, help_text='Automatically create time entries for email summaries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_panther_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PracticePanther User',
                'verbose_name_plural': 'PracticePanther Users',
            },
        ),
    ]
