# Generated by Django 5.2 on 2025-07-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Involex', '0002_cliouser_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliouser',
            name='region',
        ),
    ]
