# Generated by Django 5.2 on 2025-08-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Involex', '0003_remove_cliouser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliouser',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('CA', 'Canada')], default='NA', max_length=2),
        ),
    ]
