# Generated by Django 5.2 on 2025-08-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Involex', '0004_cliouser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliouser',
            name='selected_matter_id',
            field=models.CharField(blank=True, help_text="User's preferred matter for email analysis", max_length=100, null=True),
        ),
    ]
